-- Migration: 0016_seed_system_default_articles
-- Seeds published system-authored articles used as landing-page defaults.

INSERT OR IGNORE INTO users (
    id,
    email,
    name,
    avatar_url,
    google_id,
    role,
    is_active,
    created_at,
    updated_at
) VALUES (
    'system-zenos-author',
    'system@zenos.work',
    'Zenos System',
    NULL,
    NULL,
    'AUTHOR',
    1,
    datetime('now'),
    datetime('now')
);

INSERT OR IGNORE INTO tags (id, name, slug, tag_type, created_at) VALUES
    ('tag-tour', 'Tour', 'tour', 'topic', datetime('now')),
    ('tag-howto', 'How To', 'how-to', 'topic', datetime('now')),
    ('tag-software-writing', 'Software Writing', 'software-writing', 'topic', datetime('now')),
    ('tag-editorial', 'Editorial', 'editorial', 'topic', datetime('now'));

INSERT OR IGNORE INTO articles (
    id,
    author_id,
    approved_by,
    title,
    slug,
    subtitle,
    content,
    cover_image_url,
    read_time_minutes,
    status,
    rejection_note,
    views_count,
    likes_count,
    comments_count,
    is_featured,
    published_at,
    created_at,
    updated_at,
    last_verified_at,
    expires_at,
    moderation_state,
    moderation_note,
    seo_title,
    seo_description,
    canonical_url,
    og_image_url,
    seo_schema_type
) VALUES
    (
        'system-article-tour',
        'system-zenos-author',
        NULL,
        'Platform Tour: Start in minutes',
        'platform-tour-start-in-minutes',
        'Take a quick guided tour of writing, review, and publish workflows.',
        '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"A fast way to learn the platform"}]},{"type":"paragraph","content":[{"type":"text","text":"Zenos is built to help writers, editors, and publishing teams work in one connected space. This guided tour walks through drafting, approvals, publishing, and post-publish visibility so a new team can get productive quickly."}]},{"type":"paragraph","content":[{"type":"text","text":"Start by creating a draft, attach the right tags, review content validity dates, and then move the piece into approval. From there, approvers can review with context, authors can respond, and publishing stays governed without slowing the work down."}]},{"type":"paragraph","content":[{"type":"text","text":"Once published, the same article flows into discovery surfaces like featured content, search, trending views, and structured article pages. That means the platform tour is not just a walkthrough. It is a real example of how a story moves end-to-end in Zenos."}]}',
        'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1600&q=80',
        3,
        'PUBLISHED',
        NULL,
        320,
        28,
        6,
        1,
        datetime('now', '-1 day'),
        datetime('now', '-1 day'),
        datetime('now', '-1 day'),
        datetime('now', '-1 day'),
        '5000-12-31 23:59:00',
        'APPROVED_BY_ADMIN',
        'Seeded system article',
        'Platform Tour: Start in minutes | Zenos.work',
        'Take a guided tour through writing, review, approval, and publish workflows in Zenos.',
        'https://zenos.work/article/platform-tour-start-in-minutes',
        'https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&w=1600&q=80',
        'Article'
    ),
    (
        'system-article-howto',
        'system-zenos-author',
        NULL,
        'How-to Guide: Ship quality content',
        'how-to-guide-ship-quality-content',
        'Learn the practical steps to draft, review, and publish without bottlenecks.',
        '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"How teams move from draft to publish"}]},{"type":"paragraph","content":[{"type":"text","text":"Quality content ships reliably when teams agree on process. In Zenos, that starts with a clear draft, a strong title, a useful subtitle, and a structured tag setup that makes the story easier to review and discover."}]},{"type":"paragraph","content":[{"type":"text","text":"The next step is editorial validation. Writers set content validity dates, reviewers receive clear approval context, and SEO metadata can be tuned when needed by approvers or superadmins. This makes the publishing path explicit and repeatable."}]},{"type":"paragraph","content":[{"type":"text","text":"After approval, teams can publish with confidence and still keep operational visibility through notifications, analytics, and search filters. That combination is what helps quality content move faster without sacrificing governance."}]}',
        'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1600&q=80',
        3,
        'PUBLISHED',
        NULL,
        290,
        24,
        5,
        1,
        datetime('now', '-2 day'),
        datetime('now', '-2 day'),
        datetime('now', '-2 day'),
        datetime('now', '-2 day'),
        '5000-12-31 23:59:00',
        'APPROVED_BY_ADMIN',
        'Seeded system article',
        'How-to Guide: Ship quality content | Zenos.work',
        'A practical guide to drafting, validating, reviewing, and publishing quality content in Zenos.',
        'https://zenos.work/article/how-to-guide-ship-quality-content',
        'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=1600&q=80',
        'HowTo'
    ),
    (
        'system-article-software-writing',
        'system-zenos-author',
        NULL,
        'Software Writing: Build docs users trust',
        'software-writing-build-docs-users-trust',
        'Create clear technical writing with standards, governance, and consistency.',
        '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Documentation that earns trust"}]},{"type":"paragraph","content":[{"type":"text","text":"Software writing works best when clarity is treated as part of the product. Zenos helps teams write technical content that remains current, reviewable, and easy to find across a growing content library."}]},{"type":"paragraph","content":[{"type":"text","text":"The combination of content validity dates, structured tags, and controlled publishing makes it easier to keep technical documents accurate over time. Readers know when something was last verified, and editorial teams have a cleaner process for updates."}]},{"type":"paragraph","content":[{"type":"text","text":"That matters because trust in software documentation comes from consistency. When every guide follows a common workflow, readers get more reliable answers and teams spend less time fixing drift across articles."}]}',
        'https://images.unsplash.com/photo-1518773553398-650c184e0bb3?auto=format&fit=crop&w=1600&q=80',
        3,
        'PUBLISHED',
        NULL,
        275,
        22,
        4,
        0,
        datetime('now', '-3 day'),
        datetime('now', '-3 day'),
        datetime('now', '-3 day'),
        datetime('now', '-3 day'),
        '5000-12-31 23:59:00',
        'APPROVED_BY_ADMIN',
        'Seeded system article',
        'Software Writing: Build docs users trust | Zenos.work',
        'Use structured editorial workflows to create technical writing users can trust.',
        'https://zenos.work/article/software-writing-build-docs-users-trust',
        'https://images.unsplash.com/photo-1518773553398-650c184e0bb3?auto=format&fit=crop&w=1600&q=80',
        'TechArticle'
    ),
    (
        'system-article-spotlight',
        'system-zenos-author',
        NULL,
        'Editorial Spotlight: Inside the Zenos workflow',
        'editorial-spotlight-inside-the-zenos-workflow',
        'See how system-authored stories keep discovery surfaces populated from day one.',
        '{"type":"doc","content":[{"type":"heading","attrs":{"level":2},"content":[{"type":"text","text":"Why seeded stories matter"}]},{"type":"paragraph","content":[{"type":"text","text":"Early product experiences fall apart when discovery surfaces are empty. This spotlight article exists so new environments still feel alive, coherent, and testable before editorial teams have published their own work."}]},{"type":"paragraph","content":[{"type":"text","text":"Because the story is stored as a normal published article, it behaves exactly like real content. It appears in feeds, search, article pages, and any layout that expects live data from the database instead of frontend placeholders."}]},{"type":"paragraph","content":[{"type":"text","text":"As teams add their own work, these seeded stories can stay as evergreen onboarding examples or be replaced later with platform-owned editorial content. The important part is that the product never launches into an empty state."}]}',
        'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1600&q=80',
        3,
        'PUBLISHED',
        NULL,
        240,
        19,
        3,
        0,
        datetime('now', '-4 day'),
        datetime('now', '-4 day'),
        datetime('now', '-4 day'),
        datetime('now', '-4 day'),
        '5000-12-31 23:59:00',
        'APPROVED_BY_ADMIN',
        'Seeded system article',
        'Editorial Spotlight: Inside the Zenos workflow | Zenos.work',
        'A system-authored spotlight article that keeps landing surfaces populated with real content.',
        'https://zenos.work/article/editorial-spotlight-inside-the-zenos-workflow',
        'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?auto=format&fit=crop&w=1600&q=80',
        'Article'
    );

INSERT OR IGNORE INTO article_tags (article_id, tag_id) VALUES
    ('system-article-tour', 'tag-tour'),
    ('system-article-tour', 'tag-editorial'),
    ('system-article-howto', 'tag-howto'),
    ('system-article-howto', 'tag-editorial'),
    ('system-article-software-writing', 'tag-software-writing'),
    ('system-article-software-writing', 'tag-editorial'),
    ('system-article-spotlight', 'tag-editorial');

INSERT INTO _migrations (filename)
VALUES ('0016_seed_system_default_articles.sql');
